--- # This playbook is supposed to do the pre-deploy checks prior to running cns-deploy
- hosts: masters
  connection: ssh
  become: yes
  user: ocpadmin
  tasks:
  # check for cns-deploy on the masters
    - include: check-cns-dep.yml
  # optional iptables/firewall changes
    - include: opt-fw-changes.yml
  # ping the intended cns storage nodes from the masters
    - include: ping-nodes.yml
  # create CNS project
    - include: create-cns-proj.yml
  # give special block device access
    - include: give-spec-blk-dev-access.yml
  # deploy cns with creds to protect admin user
    - include: deploy-cns.yml
  # output something to verify CNS
    - include: verify-cns.yml
