--- # This playbook is supposed to do the pre-deploy checks prior to running cns-deploy
- hosts: all
  connection: ssh
  become: yes
  user: ocpadmin
  vars: var-to-set.yml
  tasks:
  # check for cns-deploy on the masters
    - include: check-cns-dep.yml
  # optional iptables/firewall changes
    - include: fw-changes.yml
  # ping the intended cns storage nodes from the masters
    - include: ping-nodes.yml
 
  # output something to verify CNS
    - include: verify-cns.yml
