---
- hosts: all
  tasks:
  
    - name: Install packages for CNS block
      package: name={{ item }} state=present
      with_items:
        - iscsi-initiator-utils
        - device-mapper-multipath
        - rpcbind

    - name: Enable multipathing
      shell: "mpathconf --enable"

    - name: Copy over mpath file
      copy:
        src: multipath.conf
        dest: /etc/multipath.conf
        owner: root
        group: root
        mode: 0600

    - name: Best effort SELinux labeling of multipath.conf
      shell: "restorecon  -vR /etc/multipath.conf || true"

    - name: restart multipathd
      systemd:
        name: multipathd
        state: reloaded

    - name: load rpcbind
      shell: "systemctl add-wants multi-user rpcbind.service"

    - name: start rpcbind
      systemd:
        name: rpcbind
        state: started
